/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class const_entry_iterator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected const_entry_iterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(const_entry_iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_const_entry_iterator(swigCPtr);
    }
    swigCPtr = 0;
  }

  public const_entry_iterator() {
    this(ShawnJNI.new_const_entry_iterator__SWIG_0(), true);
  }

  public const_entry_iterator(const_entry_iterator arg0) {
    this(ShawnJNI.new_const_entry_iterator__SWIG_1(const_entry_iterator.getCPtr(arg0)), true);
  }

  public const_entry_iterator(IteratorData arg0) {
    this(ShawnJNI.new_const_entry_iterator__SWIG_2(IteratorData.getCPtr(arg0)), true);
  }

  public String __ref__() {
    return ShawnJNI.const_entry_iterator___ref__(swigCPtr);
  }

  public const_entry_iterator increment() {
    return new const_entry_iterator(ShawnJNI.const_entry_iterator_increment(swigCPtr), false);
  }

  public const_entry_iterator assign(const_entry_iterator arg0) {
    return new const_entry_iterator(ShawnJNI.const_entry_iterator_assign(swigCPtr, const_entry_iterator.getCPtr(arg0)), false);
  }

  public boolean equals(const_entry_iterator arg0) {
    return ShawnJNI.const_entry_iterator_equals(swigCPtr, const_entry_iterator.getCPtr(arg0));
  }

  public boolean isDifferent(const_entry_iterator arg0) {
    return ShawnJNI.const_entry_iterator_isDifferent(swigCPtr, const_entry_iterator.getCPtr(arg0));
  }

  public boolean has_index() {
    return ShawnJNI.const_entry_iterator_has_index(swigCPtr);
  }

  public String index() {
    return ShawnJNI.const_entry_iterator_index(swigCPtr);
  }

  public String value() {
    return ShawnJNI.const_entry_iterator_value(swigCPtr);
  }

}
