/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class IteratorData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IteratorData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IteratorData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_IteratorData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void next() {
    ShawnJNI.IteratorData_next(swigCPtr);
  }

  public IteratorData clone() {
    long cPtr = ShawnJNI.IteratorData_clone(swigCPtr);
    return (cPtr == 0) ? null : new IteratorData(cPtr, false);
  }

  public boolean has_index() {
    return ShawnJNI.IteratorData_has_index(swigCPtr);
  }

  public String index() {
    return ShawnJNI.IteratorData_index(swigCPtr);
  }

  public String value() {
    return ShawnJNI.IteratorData_value(swigCPtr);
  }

  public boolean equals(IteratorData arg0) {
    return ShawnJNI.IteratorData_equals(swigCPtr, IteratorData.getCPtr(arg0));
  }

}
