/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class KeeperManaged extends RefcntPointable {
  private long swigCPtr;

  protected KeeperManaged(long cPtr, boolean cMemoryOwn) {
    super(ShawnJNI.SWIGKeeperManagedUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KeeperManaged obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_KeeperManaged(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public String name() {
    return ShawnJNI.KeeperManaged_name(swigCPtr);
  }

  public String description() {
    return ShawnJNI.KeeperManaged_description(swigCPtr);
  }

}
