/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class Message extends RefcntPointable {
  private long swigCPtr;

  protected Message(long cPtr, boolean cMemoryOwn) {
    super(ShawnJNI.SWIGMessageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Message obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_Message(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public Message() {
    this(ShawnJNI.new_Message(), true);
  }

  public boolean is_unicast() {
    return ShawnJNI.Message_is_unicast(swigCPtr);
  }

  public int unicast_target() {
    return ShawnJNI.Message_unicast_target(swigCPtr);
  }

  public boolean is_loopback_message() {
    return ShawnJNI.Message_is_loopback_message(swigCPtr);
  }

  public Node source() {
    return new Node(ShawnJNI.Message_source(swigCPtr), false);
  }

  public Node source_w() {
    return new Node(ShawnJNI.Message_source_w(swigCPtr), false);
  }

  public boolean has_source() {
    return ShawnJNI.Message_has_source(swigCPtr);
  }

  public int timestamp_simulation_round() {
    return ShawnJNI.Message_timestamp_simulation_round(swigCPtr);
  }

  public double timestamp_time() {
    return ShawnJNI.Message_timestamp_time(swigCPtr);
  }

  public void set_source(Node arg0) {
    ShawnJNI.Message_set_source(swigCPtr, Node.getCPtr(arg0));
  }

  public void set_timestamp(int arg0, double arg1) {
    ShawnJNI.Message_set_timestamp(swigCPtr, arg0, arg1);
  }

  public int size() {
    return ShawnJNI.Message_size(swigCPtr);
  }

  public void setSize(int arg0) {
    ShawnJNI.Message_setSize(swigCPtr, arg0);
  }

}
