/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class NodeChangeListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NodeChangeListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeChangeListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_NodeChangeListener(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void node_added(Node arg0) {
    ShawnJNI.NodeChangeListener_node_added(swigCPtr, Node.getCPtr(arg0));
  }

  public void node_removed(Node arg0) {
    ShawnJNI.NodeChangeListener_node_removed(swigCPtr, Node.getCPtr(arg0));
  }

  public void id_changed(int arg0, int arg1) {
    ShawnJNI.NodeChangeListener_id_changed(swigCPtr, arg0, arg1);
  }

  public boolean invalidate() {
    return ShawnJNI.NodeChangeListener_invalidate(swigCPtr);
  }

}
