/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class Node extends TagContainer {
  private long swigCPtr;

  protected Node(long cPtr, boolean cMemoryOwn) {
    super(ShawnJNI.SWIGNodeUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Node obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_Node(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public static String getWARN_HOOD_STORAGE_PARAMETER() {
    return ShawnJNI.Node_WARN_HOOD_STORAGE_PARAMETER_get();
  }

  public Node() {
    this(ShawnJNI.new_Node(), true);
  }

  public void set_real_position(Vec arg0) {
    ShawnJNI.Node_set_real_position(swigCPtr, Vec.getCPtr(arg0));
  }

  public void add_processor(SWIGTYPE_p_shawn__RefcntPointerTshawn__Processor_t arg0) {
    ShawnJNI.Node_add_processor(swigCPtr, SWIGTYPE_p_shawn__RefcntPointerTshawn__Processor_t.getCPtr(arg0));
  }

  public void set_world(World arg0) {
    ShawnJNI.Node_set_world(swigCPtr, World.getCPtr(arg0));
  }

  public void set_id(int arg0) {
    ShawnJNI.Node_set_id(swigCPtr, arg0);
  }

  public void set_label(String arg0) {
    ShawnJNI.Node_set_label(swigCPtr, arg0);
  }

  public void init() {
    ShawnJNI.Node_init(swigCPtr);
  }

  public void reset() {
    ShawnJNI.Node_reset(swigCPtr);
  }

  public void step() {
    ShawnJNI.Node_step(swigCPtr);
  }

  public void send(SWIGTYPE_p_shawn__RefcntPointerTshawn__Message_t arg0) {
    ShawnJNI.Node_send(swigCPtr, SWIGTYPE_p_shawn__RefcntPointerTshawn__Message_t.getCPtr(arg0));
  }

  public void receive(SWIGTYPE_p_shawn__RefcntPointerTshawn__Message_const_t arg0) {
    ShawnJNI.Node_receive(swigCPtr, SWIGTYPE_p_shawn__RefcntPointerTshawn__Message_const_t.getCPtr(arg0));
  }

  public void set_movement(SWIGTYPE_p_shawn__RefcntPointerTshawn__NodeMovement_t arg0) {
    ShawnJNI.Node_set_movement(swigCPtr, SWIGTYPE_p_shawn__RefcntPointerTshawn__NodeMovement_t.getCPtr(arg0));
  }

  public NodeMovement movement_w() {
    return new NodeMovement(ShawnJNI.Node_movement_w(swigCPtr), false);
  }

  public NodeMovement movement() {
    return new NodeMovement(ShawnJNI.Node_movement(swigCPtr), false);
  }

  public Vec real_position() {
    return new Vec(ShawnJNI.Node_real_position(swigCPtr), true);
  }

  public boolean has_est_position() {
    return ShawnJNI.Node_has_est_position(swigCPtr);
  }

  public void clear_est_position() {
    ShawnJNI.Node_clear_est_position(swigCPtr);
  }

  public Vec est_position() {
    return new Vec(ShawnJNI.Node_est_position(swigCPtr), false);
  }

  public void set_est_position(Vec arg0) {
    ShawnJNI.Node_set_est_position(swigCPtr, Vec.getCPtr(arg0));
  }

  public void sync_to_tags() {
    ShawnJNI.Node_sync_to_tags(swigCPtr);
  }

  public void sync_from_tags() {
    ShawnJNI.Node_sync_from_tags(swigCPtr);
  }

  public int id() {
    return ShawnJNI.Node_id(swigCPtr);
  }

  public String label() {
    return ShawnJNI.Node_label(swigCPtr);
  }

  public int simulation_round() {
    return ShawnJNI.Node_simulation_round(swigCPtr);
  }

  public double current_time() {
    return ShawnJNI.Node_current_time(swigCPtr);
  }

  public Processor.ProcessorState state() {
    return Processor.ProcessorState.swigToEnum(ShawnJNI.Node_state(swigCPtr));
  }

  public World world() {
    return new World(ShawnJNI.Node_world(swigCPtr), false);
  }

  public World world_w() {
    return new World(ShawnJNI.Node_world_w(swigCPtr), false);
  }

  public boolean is_special_node() {
    return ShawnJNI.Node_is_special_node(swigCPtr);
  }

  public SWIGTYPE_p_shawn__EdgeModel__const_adjacency_iterator begin_adjacent_nodes(SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection d) {
    return new SWIGTYPE_p_shawn__EdgeModel__const_adjacency_iterator(ShawnJNI.Node_begin_adjacent_nodes__SWIG_0(swigCPtr, SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection.getCPtr(d)), true);
  }

  public SWIGTYPE_p_shawn__EdgeModel__const_adjacency_iterator begin_adjacent_nodes() {
    return new SWIGTYPE_p_shawn__EdgeModel__const_adjacency_iterator(ShawnJNI.Node_begin_adjacent_nodes__SWIG_1(swigCPtr), true);
  }

  public SWIGTYPE_p_shawn__EdgeModel__const_adjacency_iterator end_adjacent_nodes() {
    return new SWIGTYPE_p_shawn__EdgeModel__const_adjacency_iterator(ShawnJNI.Node_end_adjacent_nodes(swigCPtr), true);
  }

  public SWIGTYPE_p_shawn__EdgeModel__adjacency_iterator begin_adjacent_nodes_w(SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection d) {
    return new SWIGTYPE_p_shawn__EdgeModel__adjacency_iterator(ShawnJNI.Node_begin_adjacent_nodes_w__SWIG_0(swigCPtr, SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection.getCPtr(d)), true);
  }

  public SWIGTYPE_p_shawn__EdgeModel__adjacency_iterator begin_adjacent_nodes_w() {
    return new SWIGTYPE_p_shawn__EdgeModel__adjacency_iterator(ShawnJNI.Node_begin_adjacent_nodes_w__SWIG_1(swigCPtr), true);
  }

  public SWIGTYPE_p_shawn__EdgeModel__adjacency_iterator end_adjacent_nodes_w() {
    return new SWIGTYPE_p_shawn__EdgeModel__adjacency_iterator(ShawnJNI.Node_end_adjacent_nodes_w(swigCPtr), true);
  }

  public int degree(SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection d) {
    return ShawnJNI.Node_degree__SWIG_0(swigCPtr, SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection.getCPtr(d));
  }

  public int degree() {
    return ShawnJNI.Node_degree__SWIG_1(swigCPtr);
  }

  public SWIGTYPE_p_shawn__RefcntPointerTshawn__Neighborhood_t neighborhood_w(int maxdist, SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection d) {
    return new SWIGTYPE_p_shawn__RefcntPointerTshawn__Neighborhood_t(ShawnJNI.Node_neighborhood_w__SWIG_0(swigCPtr, maxdist, SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection.getCPtr(d)), true);
  }

  public SWIGTYPE_p_shawn__RefcntPointerTshawn__Neighborhood_t neighborhood_w(int maxdist) {
    return new SWIGTYPE_p_shawn__RefcntPointerTshawn__Neighborhood_t(ShawnJNI.Node_neighborhood_w__SWIG_1(swigCPtr, maxdist), true);
  }

  public SWIGTYPE_p_shawn__RefcntPointerTshawn__NeighborhoodConst_t neighborhood(int maxdist, SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection d) {
    return new SWIGTYPE_p_shawn__RefcntPointerTshawn__NeighborhoodConst_t(ShawnJNI.Node_neighborhood__SWIG_0(swigCPtr, maxdist, SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection.getCPtr(d)), true);
  }

  public SWIGTYPE_p_shawn__RefcntPointerTshawn__NeighborhoodConst_t neighborhood(int maxdist) {
    return new SWIGTYPE_p_shawn__RefcntPointerTshawn__NeighborhoodConst_t(ShawnJNI.Node_neighborhood__SWIG_1(swigCPtr, maxdist), true);
  }

  public boolean equals(Node n) {
    return ShawnJNI.Node_equals(swigCPtr, Node.getCPtr(n));
  }

  public boolean isDifferent(Node n) {
    return ShawnJNI.Node_isDifferent(swigCPtr, Node.getCPtr(n));
  }

  public boolean has_fixpoint() {
    return ShawnJNI.Node_has_fixpoint(swigCPtr);
  }

  public int component_extension() {
    return ShawnJNI.Node_component_extension(swigCPtr);
  }

  public SWIGTYPE_p_std__setTshawn__Node_const_p_t get_adjacent_nodes(SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection d) {
    return new SWIGTYPE_p_std__setTshawn__Node_const_p_t(ShawnJNI.Node_get_adjacent_nodes__SWIG_0(swigCPtr, SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection.getCPtr(d)), true);
  }

  public SWIGTYPE_p_std__setTshawn__Node_const_p_t get_adjacent_nodes() {
    return new SWIGTYPE_p_std__setTshawn__Node_const_p_t(ShawnJNI.Node_get_adjacent_nodes__SWIG_1(swigCPtr), true);
  }

  public SWIGTYPE_p_std__setTshawn__Node_p_t get_adjacent_nodes_w(SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection d) {
    return new SWIGTYPE_p_std__setTshawn__Node_p_t(ShawnJNI.Node_get_adjacent_nodes_w__SWIG_0(swigCPtr, SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection.getCPtr(d)), true);
  }

  public SWIGTYPE_p_std__setTshawn__Node_p_t get_adjacent_nodes_w() {
    return new SWIGTYPE_p_std__setTshawn__Node_p_t(ShawnJNI.Node_get_adjacent_nodes_w__SWIG_1(swigCPtr), true);
  }

}
