/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class NodeMovement extends RefcntPointable {
  private long swigCPtr;

  protected NodeMovement(long cPtr, boolean cMemoryOwn) {
    super(ShawnJNI.SWIGNodeMovementUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeMovement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_NodeMovement(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public void init(Node arg0) {
    ShawnJNI.NodeMovement_init(swigCPtr, Node.getCPtr(arg0));
  }

  public void init_from(Node arg0, NodeMovement arg1) {
    ShawnJNI.NodeMovement_init_from(swigCPtr, Node.getCPtr(arg0), NodeMovement.getCPtr(arg1));
  }

  public boolean set_position(Vec arg0) {
    return ShawnJNI.NodeMovement_set_position(swigCPtr, Vec.getCPtr(arg0));
  }

  public Vec position() {
    return new Vec(ShawnJNI.NodeMovement_position(swigCPtr), true);
  }

  public Vec velocity() {
    return new Vec(ShawnJNI.NodeMovement_velocity(swigCPtr), true);
  }

  public String name() {
    return ShawnJNI.NodeMovement_name(swigCPtr);
  }

  public int simulation_round() {
    return ShawnJNI.NodeMovement_simulation_round(swigCPtr);
  }

  public double current_time() {
    return ShawnJNI.NodeMovement_current_time(swigCPtr);
  }

  public World world() {
    return new World(ShawnJNI.NodeMovement_world(swigCPtr), false);
  }

  public World world_w() {
    return new World(ShawnJNI.NodeMovement_world_w(swigCPtr), false);
  }

  public Node node_w() {
    return new Node(ShawnJNI.NodeMovement_node_w(swigCPtr), false);
  }

  public Node node() {
    return new Node(ShawnJNI.NodeMovement_node(swigCPtr), false);
  }

}
