/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class RefcntPointable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RefcntPointable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RefcntPointable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_RefcntPointable(swigCPtr);
    }
    swigCPtr = 0;
  }

  public RefcntPointable() {
    this(ShawnJNI.new_RefcntPointable(), true);
  }

  public void setReference_counter_(int value) {
    ShawnJNI.RefcntPointable_reference_counter__set(swigCPtr, value);
  }

  public int getReference_counter_() {
    return ShawnJNI.RefcntPointable_reference_counter__get(swigCPtr);
  }

}
