/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class RefcntPointer_ConstTag {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RefcntPointer_ConstTag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RefcntPointer_ConstTag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_RefcntPointer_ConstTag(swigCPtr);
    }
    swigCPtr = 0;
  }

  public RefcntPointer_ConstTag() {
    this(ShawnJNI.new_RefcntPointer_ConstTag__SWIG_0(), true);
  }

  public RefcntPointer_ConstTag(Tag t) {
    this(ShawnJNI.new_RefcntPointer_ConstTag__SWIG_1(Tag.getCPtr(t)), true);
  }

  public RefcntPointer_ConstTag(RefcntPointer_ConstTag t) {
    this(ShawnJNI.new_RefcntPointer_ConstTag__SWIG_2(RefcntPointer_ConstTag.getCPtr(t)), true);
  }

  public boolean is_null() {
    return ShawnJNI.RefcntPointer_ConstTag_is_null(swigCPtr);
  }

  public boolean is_not_null() {
    return ShawnJNI.RefcntPointer_ConstTag_is_not_null(swigCPtr);
  }

  public Tag __ref__() {
    return new Tag(ShawnJNI.RefcntPointer_ConstTag___ref__(swigCPtr), false);
  }

  public Tag __deref__() {
    long cPtr = ShawnJNI.RefcntPointer_ConstTag___deref__(swigCPtr);
    return (cPtr == 0) ? null : new Tag(cPtr, false);
  }

  public Tag get() {
    long cPtr = ShawnJNI.RefcntPointer_ConstTag_get(swigCPtr);
    return (cPtr == 0) ? null : new Tag(cPtr, false);
  }

  public RefcntPointer_ConstTag assign(RefcntPointer_ConstTag s) {
    return new RefcntPointer_ConstTag(ShawnJNI.RefcntPointer_ConstTag_assign__SWIG_0(swigCPtr, RefcntPointer_ConstTag.getCPtr(s)), false);
  }

  public RefcntPointer_ConstTag assign(Tag t) {
    return new RefcntPointer_ConstTag(ShawnJNI.RefcntPointer_ConstTag_assign__SWIG_1(swigCPtr, Tag.getCPtr(t)), false);
  }

  public boolean lesserThan(RefcntPointer_ConstTag s) {
    return ShawnJNI.RefcntPointer_ConstTag_lesserThan__SWIG_0(swigCPtr, RefcntPointer_ConstTag.getCPtr(s));
  }

  public boolean lesserEqual(RefcntPointer_ConstTag s) {
    return ShawnJNI.RefcntPointer_ConstTag_lesserEqual__SWIG_0(swigCPtr, RefcntPointer_ConstTag.getCPtr(s));
  }

  public boolean greaterThan(RefcntPointer_ConstTag s) {
    return ShawnJNI.RefcntPointer_ConstTag_greaterThan__SWIG_0(swigCPtr, RefcntPointer_ConstTag.getCPtr(s));
  }

  public boolean greaterEqual(RefcntPointer_ConstTag s) {
    return ShawnJNI.RefcntPointer_ConstTag_greaterEqual__SWIG_0(swigCPtr, RefcntPointer_ConstTag.getCPtr(s));
  }

  public boolean equals(RefcntPointer_ConstTag s) {
    return ShawnJNI.RefcntPointer_ConstTag_equals__SWIG_0(swigCPtr, RefcntPointer_ConstTag.getCPtr(s));
  }

  public boolean isDifferent(RefcntPointer_ConstTag s) {
    return ShawnJNI.RefcntPointer_ConstTag_isDifferent__SWIG_0(swigCPtr, RefcntPointer_ConstTag.getCPtr(s));
  }

  public boolean lesserThan(Tag s) {
    return ShawnJNI.RefcntPointer_ConstTag_lesserThan__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean lesserEqual(Tag s) {
    return ShawnJNI.RefcntPointer_ConstTag_lesserEqual__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean greaterThan(Tag s) {
    return ShawnJNI.RefcntPointer_ConstTag_greaterThan__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean greaterEqual(Tag s) {
    return ShawnJNI.RefcntPointer_ConstTag_greaterEqual__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean equals(Tag s) {
    return ShawnJNI.RefcntPointer_ConstTag_equals__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean isDifferent(Tag s) {
    return ShawnJNI.RefcntPointer_ConstTag_isDifferent__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public String name() {
    return ShawnJNI.RefcntPointer_ConstTag_name(swigCPtr);
  }

  public boolean is_locked() {
    return ShawnJNI.RefcntPointer_ConstTag_is_locked(swigCPtr);
  }

  public String type_identifier() {
    return ShawnJNI.RefcntPointer_ConstTag_type_identifier(swigCPtr);
  }

  public String encoded_content() {
    return ShawnJNI.RefcntPointer_ConstTag_encoded_content(swigCPtr);
  }

  public boolean is_persistent() {
    return ShawnJNI.RefcntPointer_ConstTag_is_persistent(swigCPtr);
  }

  public const_entry_iterator begin_entries() {
    return new const_entry_iterator(ShawnJNI.RefcntPointer_ConstTag_begin_entries(swigCPtr), true);
  }

  public const_entry_iterator end_entries() {
    return new const_entry_iterator(ShawnJNI.RefcntPointer_ConstTag_end_entries(swigCPtr), true);
  }

  public RefcntPointer_ConstTag find_tag(String arg0) {
    return new RefcntPointer_ConstTag(ShawnJNI.RefcntPointer_ConstTag_find_tag(swigCPtr, arg0), true);
  }

  public SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator begin_tags() {
    return new SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator(ShawnJNI.RefcntPointer_ConstTag_begin_tags(swigCPtr), true);
  }

  public SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator end_tags() {
    return new SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator(ShawnJNI.RefcntPointer_ConstTag_end_tags(swigCPtr), true);
  }

  public long count_tags() {
    return ShawnJNI.RefcntPointer_ConstTag_count_tags(swigCPtr);
  }

  public int getReference_counter_() {
    return ShawnJNI.RefcntPointer_ConstTag_reference_counter__get(swigCPtr);
  }

}
