/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class RefcntPointer_Tag {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RefcntPointer_Tag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RefcntPointer_Tag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_RefcntPointer_Tag(swigCPtr);
    }
    swigCPtr = 0;
  }

  public RefcntPointer_Tag() {
    this(ShawnJNI.new_RefcntPointer_Tag__SWIG_0(), true);
  }

  public RefcntPointer_Tag(Tag t) {
    this(ShawnJNI.new_RefcntPointer_Tag__SWIG_1(Tag.getCPtr(t)), true);
  }

  public RefcntPointer_Tag(RefcntPointer_Tag t) {
    this(ShawnJNI.new_RefcntPointer_Tag__SWIG_2(RefcntPointer_Tag.getCPtr(t)), true);
  }

  public boolean is_null() {
    return ShawnJNI.RefcntPointer_Tag_is_null(swigCPtr);
  }

  public boolean is_not_null() {
    return ShawnJNI.RefcntPointer_Tag_is_not_null(swigCPtr);
  }

  public Tag __ref__() {
    return new Tag(ShawnJNI.RefcntPointer_Tag___ref__(swigCPtr), false);
  }

  public Tag __deref__() {
    long cPtr = ShawnJNI.RefcntPointer_Tag___deref__(swigCPtr);
    return (cPtr == 0) ? null : new Tag(cPtr, false);
  }

  public Tag get() {
    long cPtr = ShawnJNI.RefcntPointer_Tag_get(swigCPtr);
    return (cPtr == 0) ? null : new Tag(cPtr, false);
  }

  public RefcntPointer_Tag assign(RefcntPointer_Tag s) {
    return new RefcntPointer_Tag(ShawnJNI.RefcntPointer_Tag_assign__SWIG_0(swigCPtr, RefcntPointer_Tag.getCPtr(s)), false);
  }

  public RefcntPointer_Tag assign(Tag t) {
    return new RefcntPointer_Tag(ShawnJNI.RefcntPointer_Tag_assign__SWIG_1(swigCPtr, Tag.getCPtr(t)), false);
  }

  public boolean lesserThan(RefcntPointer_Tag s) {
    return ShawnJNI.RefcntPointer_Tag_lesserThan__SWIG_0(swigCPtr, RefcntPointer_Tag.getCPtr(s));
  }

  public boolean lesserEqual(RefcntPointer_Tag s) {
    return ShawnJNI.RefcntPointer_Tag_lesserEqual__SWIG_0(swigCPtr, RefcntPointer_Tag.getCPtr(s));
  }

  public boolean greaterThan(RefcntPointer_Tag s) {
    return ShawnJNI.RefcntPointer_Tag_greaterThan__SWIG_0(swigCPtr, RefcntPointer_Tag.getCPtr(s));
  }

  public boolean greaterEqual(RefcntPointer_Tag s) {
    return ShawnJNI.RefcntPointer_Tag_greaterEqual__SWIG_0(swigCPtr, RefcntPointer_Tag.getCPtr(s));
  }

  public boolean equals(RefcntPointer_Tag s) {
    return ShawnJNI.RefcntPointer_Tag_equals__SWIG_0(swigCPtr, RefcntPointer_Tag.getCPtr(s));
  }

  public boolean isDifferent(RefcntPointer_Tag s) {
    return ShawnJNI.RefcntPointer_Tag_isDifferent__SWIG_0(swigCPtr, RefcntPointer_Tag.getCPtr(s));
  }

  public boolean lesserThan(Tag s) {
    return ShawnJNI.RefcntPointer_Tag_lesserThan__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean lesserEqual(Tag s) {
    return ShawnJNI.RefcntPointer_Tag_lesserEqual__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean greaterThan(Tag s) {
    return ShawnJNI.RefcntPointer_Tag_greaterThan__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean greaterEqual(Tag s) {
    return ShawnJNI.RefcntPointer_Tag_greaterEqual__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean equals(Tag s) {
    return ShawnJNI.RefcntPointer_Tag_equals__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public boolean isDifferent(Tag s) {
    return ShawnJNI.RefcntPointer_Tag_isDifferent__SWIG_1(swigCPtr, Tag.getCPtr(s));
  }

  public String name() {
    return ShawnJNI.RefcntPointer_Tag_name(swigCPtr);
  }

  public boolean is_locked() {
    return ShawnJNI.RefcntPointer_Tag_is_locked(swigCPtr);
  }

  public void lock() {
    ShawnJNI.RefcntPointer_Tag_lock(swigCPtr);
  }

  public void unlock() {
    ShawnJNI.RefcntPointer_Tag_unlock(swigCPtr);
  }

  public String type_identifier() {
    return ShawnJNI.RefcntPointer_Tag_type_identifier(swigCPtr);
  }

  public String encoded_content() {
    return ShawnJNI.RefcntPointer_Tag_encoded_content(swigCPtr);
  }

  public void set_persistency(boolean arg0) {
    ShawnJNI.RefcntPointer_Tag_set_persistency(swigCPtr, arg0);
  }

  public boolean is_persistent() {
    return ShawnJNI.RefcntPointer_Tag_is_persistent(swigCPtr);
  }

  public const_entry_iterator begin_entries() {
    return new const_entry_iterator(ShawnJNI.RefcntPointer_Tag_begin_entries(swigCPtr), true);
  }

  public const_entry_iterator end_entries() {
    return new const_entry_iterator(ShawnJNI.RefcntPointer_Tag_end_entries(swigCPtr), true);
  }

  public void add_indexed_entry(String index, String value) {
    ShawnJNI.RefcntPointer_Tag_add_indexed_entry(swigCPtr, index, value);
  }

  public void add_value_entry(String value) {
    ShawnJNI.RefcntPointer_Tag_add_value_entry(swigCPtr, value);
  }

  public void add_tag(RefcntPointer_Tag arg0) {
    ShawnJNI.RefcntPointer_Tag_add_tag(swigCPtr, RefcntPointer_Tag.getCPtr(arg0));
  }

  public void remove_tag(RefcntPointer_ConstTag arg0) {
    ShawnJNI.RefcntPointer_Tag_remove_tag(swigCPtr, RefcntPointer_ConstTag.getCPtr(arg0));
  }

  public void remove_tag_by_name(String arg0) {
    ShawnJNI.RefcntPointer_Tag_remove_tag_by_name(swigCPtr, arg0);
  }

  public void clear_tags() {
    ShawnJNI.RefcntPointer_Tag_clear_tags(swigCPtr);
  }

  public RefcntPointer_ConstTag find_tag(String arg0) {
    return new RefcntPointer_ConstTag(ShawnJNI.RefcntPointer_Tag_find_tag(swigCPtr, arg0), true);
  }

  public RefcntPointer_Tag find_tag_w(String arg0) {
    return new RefcntPointer_Tag(ShawnJNI.RefcntPointer_Tag_find_tag_w(swigCPtr, arg0), true);
  }

  public SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator begin_tags() {
    return new SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator(ShawnJNI.RefcntPointer_Tag_begin_tags(swigCPtr), true);
  }

  public SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator end_tags() {
    return new SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator(ShawnJNI.RefcntPointer_Tag_end_tags(swigCPtr), true);
  }

  public long count_tags() {
    return ShawnJNI.RefcntPointer_Tag_count_tags(swigCPtr);
  }

  public void setReference_counter_(int value) {
    ShawnJNI.RefcntPointer_Tag_reference_counter__set(swigCPtr, value);
  }

  public int getReference_counter_() {
    return ShawnJNI.RefcntPointer_Tag_reference_counter__get(swigCPtr);
  }

}
