/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class ShawnSimulationController extends SimulationController {
  private long swigCPtr;

  protected ShawnSimulationController(long cPtr, boolean cMemoryOwn) {
    super(ShawnJNI.SWIGShawnSimulationControllerUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShawnSimulationController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_ShawnSimulationController(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public ShawnSimulationController() {
    this(ShawnJNI.new_ShawnSimulationController(), true);
  }

  public static String getWHITE_SPACE() {
    return ShawnJNI.ShawnSimulationController_WHITE_SPACE_get();
  }

  public void execute_command_line(String arg0) {
    ShawnJNI.ShawnSimulationController_execute_command_line(swigCPtr, arg0);
  }

  public void execute_task(SWIGTYPE_p_shawn__RefcntPointerTshawn__SimulationTask_t arg0) {
    ShawnJNI.ShawnSimulationController_execute_task(swigCPtr, SWIGTYPE_p_shawn__RefcntPointerTshawn__SimulationTask_t.getCPtr(arg0));
  }

}
