/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class Shawn implements ShawnConstants {
  public static double euclidean_distance(Vec p1, Vec p2) {
    return ShawnJNI.euclidean_distance(Vec.getCPtr(p1), Vec.getCPtr(p2));
  }

  public static Vec cross_product(Vec p1, Vec p2) {
    return new Vec(ShawnJNI.cross_product(Vec.getCPtr(p1), Vec.getCPtr(p2)), true);
  }

  public static ShawnSimulationController master_init() {
    long cPtr = ShawnJNI.master_init();
    return (cPtr == 0) ? null : new ShawnSimulationController(cPtr, false);
  }

}
