/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class SimulationTaskResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SimulationTaskResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SimulationTaskResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_SimulationTaskResult(swigCPtr);
    }
    swigCPtr = 0;
  }

  public String name() {
    return ShawnJNI.SimulationTaskResult_name(swigCPtr);
  }

  public String description() {
    return ShawnJNI.SimulationTaskResult_description(swigCPtr);
  }

  public void send_to(SWIGTYPE_p_std__ostream arg0) {
    ShawnJNI.SimulationTaskResult_send_to(swigCPtr, SWIGTYPE_p_std__ostream.getCPtr(arg0));
  }

}
