/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class SimulationEnvironment extends TagContainer {
  private long swigCPtr;

  protected SimulationEnvironment(long cPtr, boolean cMemoryOwn) {
    super(ShawnJNI.SWIGSimulationEnvironmentUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SimulationEnvironment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_SimulationEnvironment(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SimulationEnvironment() {
    this(ShawnJNI.new_SimulationEnvironment(), true);
  }

  public void push_parameters(SWIGTYPE_p_shawn__RefcntPointerTshawn__ParameterSet_t arg0) {
    ShawnJNI.SimulationEnvironment_push_parameters(swigCPtr, SWIGTYPE_p_shawn__RefcntPointerTshawn__ParameterSet_t.getCPtr(arg0));
  }

  public void pop_parameters() {
    ShawnJNI.SimulationEnvironment_pop_parameters(swigCPtr);
  }

  public void add_parameters_low_prio(SWIGTYPE_p_shawn__RefcntPointerTshawn__ParameterSet_t arg0) {
    ShawnJNI.SimulationEnvironment_add_parameters_low_prio(swigCPtr, SWIGTYPE_p_shawn__RefcntPointerTshawn__ParameterSet_t.getCPtr(arg0));
  }

  public void add_parameters_high_prio(SWIGTYPE_p_shawn__RefcntPointerTshawn__ParameterSet_t arg0) {
    ShawnJNI.SimulationEnvironment_add_parameters_high_prio(swigCPtr, SWIGTYPE_p_shawn__RefcntPointerTshawn__ParameterSet_t.getCPtr(arg0));
  }

  public void add_parameter_low_prio(String arg0, String arg1) {
    ShawnJNI.SimulationEnvironment_add_parameter_low_prio(swigCPtr, arg0, arg1);
  }

  public void add_parameter_high_prio(String arg0, String arg1) {
    ShawnJNI.SimulationEnvironment_add_parameter_high_prio(swigCPtr, arg0, arg1);
  }

  public String required_string_param(String arg0) {
    return ShawnJNI.SimulationEnvironment_required_string_param(swigCPtr, arg0);
  }

  public String optional_string_param(String arg0, String arg1, SWIGTYPE_p_bool is_set) {
    return ShawnJNI.SimulationEnvironment_optional_string_param__SWIG_0(swigCPtr, arg0, arg1, SWIGTYPE_p_bool.getCPtr(is_set));
  }

  public String optional_string_param(String arg0, String arg1) {
    return ShawnJNI.SimulationEnvironment_optional_string_param__SWIG_1(swigCPtr, arg0, arg1);
  }

  public int required_int_param(String arg0) {
    return ShawnJNI.SimulationEnvironment_required_int_param(swigCPtr, arg0);
  }

  public int optional_int_param(String arg0, int arg1, SWIGTYPE_p_bool is_set) {
    return ShawnJNI.SimulationEnvironment_optional_int_param__SWIG_0(swigCPtr, arg0, arg1, SWIGTYPE_p_bool.getCPtr(is_set));
  }

  public int optional_int_param(String arg0, int arg1) {
    return ShawnJNI.SimulationEnvironment_optional_int_param__SWIG_1(swigCPtr, arg0, arg1);
  }

  public double required_double_param(String arg0) {
    return ShawnJNI.SimulationEnvironment_required_double_param(swigCPtr, arg0);
  }

  public double optional_double_param(String arg0, double arg1, SWIGTYPE_p_bool is_set) {
    return ShawnJNI.SimulationEnvironment_optional_double_param__SWIG_0(swigCPtr, arg0, arg1, SWIGTYPE_p_bool.getCPtr(is_set));
  }

  public double optional_double_param(String arg0, double arg1) {
    return ShawnJNI.SimulationEnvironment_optional_double_param__SWIG_1(swigCPtr, arg0, arg1);
  }

  public boolean required_bool_param(String arg0) {
    return ShawnJNI.SimulationEnvironment_required_bool_param(swigCPtr, arg0);
  }

  public boolean optional_bool_param(String arg0, boolean arg1, SWIGTYPE_p_bool is_set) {
    return ShawnJNI.SimulationEnvironment_optional_bool_param__SWIG_0(swigCPtr, arg0, arg1, SWIGTYPE_p_bool.getCPtr(is_set));
  }

  public boolean optional_bool_param(String arg0, boolean arg1) {
    return ShawnJNI.SimulationEnvironment_optional_bool_param__SWIG_1(swigCPtr, arg0, arg1);
  }

  public boolean find_param(String arg0, SWIGTYPE_p_std__string arg1) {
    return ShawnJNI.SimulationEnvironment_find_param(swigCPtr, arg0, SWIGTYPE_p_std__string.getCPtr(arg1));
  }

}
