/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection {
  private long swigCPtr;

  protected SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_shawn__EdgeModel__CommunicationDirection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

