/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class SWIGTYPE_p_shawn__SkipNullIteratorTshawn__Node_const_std__vectorTshawn__Node_p_t_shawn__World__NodeVector__const_iterator_t {
  private long swigCPtr;

  protected SWIGTYPE_p_shawn__SkipNullIteratorTshawn__Node_const_std__vectorTshawn__Node_p_t_shawn__World__NodeVector__const_iterator_t(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_shawn__SkipNullIteratorTshawn__Node_const_std__vectorTshawn__Node_p_t_shawn__World__NodeVector__const_iterator_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_shawn__SkipNullIteratorTshawn__Node_const_std__vectorTshawn__Node_p_t_shawn__World__NodeVector__const_iterator_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

