/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.swarmnet.shawn;

public class TagContainer extends RefcntPointable {
  private long swigCPtr;

  protected TagContainer(long cPtr, boolean cMemoryOwn) {
    super(ShawnJNI.SWIGTagContainerUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TagContainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ShawnJNI.delete_TagContainer(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public TagContainer() {
    this(ShawnJNI.new_TagContainer(), true);
  }

  public void add_tag(RefcntPointer_Tag arg0) {
    ShawnJNI.TagContainer_add_tag(swigCPtr, RefcntPointer_Tag.getCPtr(arg0));
  }

  public void remove_tag(RefcntPointer_ConstTag arg0) {
    ShawnJNI.TagContainer_remove_tag(swigCPtr, RefcntPointer_ConstTag.getCPtr(arg0));
  }

  public void remove_tag_by_name(String arg0) {
    ShawnJNI.TagContainer_remove_tag_by_name(swigCPtr, arg0);
  }

  public void clear_tags() {
    ShawnJNI.TagContainer_clear_tags(swigCPtr);
  }

  public RefcntPointer_ConstTag find_tag(String arg0) {
    return new RefcntPointer_ConstTag(ShawnJNI.TagContainer_find_tag(swigCPtr, arg0), true);
  }

  public RefcntPointer_Tag find_tag_w(String arg0) {
    return new RefcntPointer_Tag(ShawnJNI.TagContainer_find_tag_w(swigCPtr, arg0), true);
  }

  public SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator begin_tags() {
    return new SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator(ShawnJNI.TagContainer_begin_tags(swigCPtr), true);
  }

  public SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator end_tags() {
    return new SWIGTYPE_p_shawn__TagContainer__TagMap__const_iterator(ShawnJNI.TagContainer_end_tags(swigCPtr), true);
  }

  public long count_tags() {
    return ShawnJNI.TagContainer_count_tags(swigCPtr);
  }

}
