
/**********************************************************************

        Header generated by generateRevisionHeader.py, DO NOT EDIT

        This is the default version of the generated header in case
        generation is not possible. Otherwise it will be overwritten.

        Generation will be initiated by custom command in CMakeLists.txt
        after checking if Python is available. The name of this header
        and the used identifiers are supplied as arguments there.

**********************************************************************/

#ifndef SHAWN_MAIN_SRC_REVISION_H
#define SHAWN_MAIN_SRC_REVISION_H

#include <string>

namespace git
{

const std::string revision = "git-version not determinable";

}   // namespace git


#endif  // #ifndef SHAWN_MAIN_SRC_REVISION_H

